---
- name: qarnot dependencies | Installing jq
  apt:
    name: jq
  become: true

- name: qarnot dependencies | Installing curl
  apt:
    name: curl
  become: true

- name: qarnot dependencies | Installing cifs-utils
  apt:
    name: cifs-utils
  become: true
